name: Check subfolders in Node SDK with yarn audit

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - COR-2064/yarn-audit
  schedule:
    - cron: '0 12 * * *' # run every day at 12  
  # Allows us to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  yarn-audit:
    name: Yarn Audit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: [.]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        working-directory: ${{ matrix.folder }}
        run: yarn install --immutable

      - name: Run yarn audit
        working-directory: ${{ matrix.folder }}
        run: yarn npm audit --all --recursive --severity high

