name: Check subfolders in Node SDK with yarn audit

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main 
      - COR-2064/yarn-audit
  schedule:
    - cron: '0 12 * * *' # run every day at 12  
  # Allows us to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  yarn-audit:
    name: Yarn Audit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: [.]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        working-directory: ${{ matrix.folder }}
        run: yarn install --immutable

      - name: Run yarn audit
        working-directory: ${{ matrix.folder }}
        run: |
          AUDIT_OUTPUT=$(yarn npm audit --all --recursive || true)
          echo "$AUDIT_OUTPUT"
          if echo "$AUDIT_OUTPUT" | grep -Ei "severity: (high|critical)"; then
            echo "High or Critical vulnerabilities found!"
            exit 1
          else
            echo "No high-risk vulnerabilities found."
            exit 0
          fi 

      - name: Report Status to Slack    # This step only runs if a previous step failed
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SECURITY_ADVISORIES_SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "Yarn Audit detected vulnerabilities on : ${{ matrix.directory }}"
          SLACK_MESSAGE: |
              Yarn audit detected vulnerabilities for *${{ matrix.directory }}*. 
              Please check the GitHub Actions logs.
              *View Logs:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Click here to open the Summary page>
          SLACK_USERNAME: YarnAuditBot

